//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Garagiste
    {
        public Garagiste()
        {
            this.PeriodeFermeture = new HashSet<PeriodeFermeture>();
            this.Reparation = new HashSet<Reparation>();
        }
    
        public int ID { get; set; }
        public string Nom { get; set; }
    
        public virtual ICollection<PeriodeFermeture> PeriodeFermeture { get; set; }
        public virtual Franchise Franchise { get; set; }
        public virtual ICollection<Reparation> Reparation { get; set; }
    }
}
