//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modele
    {
        public Modele()
        {
            this.Voiture = new HashSet<Voiture>();
            this.Revision = new HashSet<Revision>();
        }
    
        public int ID { get; set; }
        public string Nom { get; set; }
    
        public virtual ICollection<Voiture> Voiture { get; set; }
        public virtual Marque Marque { get; set; }
        public virtual ICollection<Revision> Revision { get; set; }
    }
}
