//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revision
    {
        public Revision()
        {
            this.Reparation = new HashSet<Reparation>();
        }
    
        public int ID { get; set; }
        public string Libelle { get; set; }
        public double Kilometrage { get; set; }
        public System.TimeSpan DureeIntervention { get; set; }
    
        public virtual Modele Modele { get; set; }
        public virtual Marque Marque { get; set; }
        public virtual ICollection<Reparation> Reparation { get; set; }
    }
}
